package com.engfred.lockit.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Serene blue primary for trust, green tertiary for security)
val PrimaryLight = Color(0xFF2962FF)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDCE4FF)
val OnPrimaryContainerLight = Color(0xFF001A48)

val SecondaryLight = Color(0xFF555F71)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDCE4F8)
val OnSecondaryContainerLight = Color(0xFF121C2B)

val TertiaryLight = Color(0xFF006C4F)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFF8DF5CD)
val OnTertiaryContainerLight = Color(0xFF002116)

val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val BackgroundLight = Color(0xFFFEFBFF)
val OnBackgroundLight = Color(0xFF1B1B1F)
val SurfaceLight = Color(0xFFFEFBFF)
val OnSurfaceLight = Color(0xFF1B1B1F)
val SurfaceVariantLight = Color(0xFFE0E2EC)
val OnSurfaceVariantLight = Color(0xFF434750)
val OutlineLight = Color(0xFF74777F)
val OutlineVariantLight = Color(0xFFC4C6D0)
val ScrimLight = Color(0xFF000000)
val InverseSurfaceLight = Color(0xFF303033)
val InverseOnSurfaceLight = Color(0xFFF2F0F4)
val InversePrimaryLight = Color(0xFFB5C8FF)

// Dark Theme Colors (Lighter blues/greens for visibility, dark neutrals for premium depth)
val PrimaryDark = Color(0xFFB5C8FF)
val OnPrimaryDark = Color(0xFF00327A)
val PrimaryContainerDark = Color(0xFF0049AA)
val OnPrimaryContainerDark = Color(0xFFDCE4FF)

val SecondaryDark = Color(0xFFC0C8DC)
val OnSecondaryDark = Color(0xFF273141)
val SecondaryContainerDark = Color(0xFF3D4759)
val OnSecondaryContainerDark = Color(0xFFDCE4F8)

val TertiaryDark = Color(0xFF71D8B1)
val OnTertiaryDark = Color(0xFF003A29)
val TertiaryContainerDark = Color(0xFF00513A)
val OnTertiaryContainerDark = Color(0xFF8DF5CD)

val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val BackgroundDark = Color(0xFF1B1B1F)
val OnBackgroundDark = Color(0xFFE3E2E6)
val SurfaceDark = Color(0xFF1B1B1F)
val OnSurfaceDark = Color(0xFFE3E2E6)
val SurfaceVariantDark = Color(0xFF434750)
val OnSurfaceVariantDark = Color(0xFFC4C6D0)
val OutlineDark = Color(0xFF8E9099)
val OutlineVariantDark = Color(0xFF434750)
val ScrimDark = Color(0xFF000000)
val InverseSurfaceDark = Color(0xFFE3E2E6)
val InverseOnSurfaceDark = Color(0xFF303033)
val InversePrimaryDark = Color(0xFF2962FF)